-- V1 : schéma initial. Reflet exact des entités JPA
-- (ddl-auto=validate vérifie la concordance à chaque démarrage).
-- Les données de démo restent dans DataInitializer (dates relatives à aujourd'hui).

CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    telephone VARCHAR(255)
);

CREATE TABLE services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    categorie VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    duree_minutes INTEGER NOT NULL,
    prix NUMERIC(10, 2),
    capacite_defaut INTEGER NOT NULL,
    icone VARCHAR(255)
);

CREATE TABLE resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    type VARCHAR(255),
    categorie VARCHAR(255) NOT NULL,
    capacite INTEGER NOT NULL,
    localisation VARCHAR(255)
);

CREATE TABLE time_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id BIGINT NOT NULL,
    resource_id BIGINT NOT NULL,
    debut TIMESTAMP NOT NULL,
    fin TIMESTAMP NOT NULL,
    places_totales INTEGER NOT NULL,
    places_reservees INTEGER NOT NULL,
    statut VARCHAR(255),
    version BIGINT,
    CONSTRAINT fk_slot_service FOREIGN KEY (service_id) REFERENCES services (id),
    CONSTRAINT fk_slot_resource FOREIGN KEY (resource_id) REFERENCES resources (id)
);

CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(12) NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL,
    slot_id BIGINT NOT NULL,
    nb_places INTEGER NOT NULL,
    statut VARCHAR(255),
    cree_le TIMESTAMP,
    annule_le TIMESTAMP,
    CONSTRAINT fk_booking_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT fk_booking_slot FOREIGN KEY (slot_id) REFERENCES time_slots (id)
);
